From 5e9c6b9175d66170ef65fc703f2e46788a59ca0c Mon Sep 17 00:00:00 2001
From: SethMichaelLarson <sethmichaellarson@protonmail.com>
Date: Sun, 25 Mar 2018 20:52:13 -0500
Subject: [PATCH] Fix AppEngine connection pool tests

---
 test/appengine/test_gae_manager.py           | 4 ++++
 test/with_dummyserver/test_connectionpool.py | 9 ++++++---
 2 files changed, 10 insertions(+), 3 deletions(-)

diff --git a/test/appengine/test_gae_manager.py b/test/appengine/test_gae_manager.py
index 95838ef89..2eb1861e0 100644
--- a/test/appengine/test_gae_manager.py
+++ b/test/appengine/test_gae_manager.py
@@ -176,6 +176,10 @@ def test_retry_return_in_response(self):
     test_retry_redirect_history = None
     test_multi_redirect_history = None
 
+    # GAE doesn't have the assert_same_host parameter in urlopen()
+    test_redirect_cross_host_forward_auth_headers = None
+    test_redirect_cross_host_no_forward_auth_headers = None
+
 
 @pytest.mark.usefixtures('testbed')
 class TestGAERetryAfter(test_connectionpool.TestRetryAfter):
diff --git a/test/with_dummyserver/test_connectionpool.py b/test/with_dummyserver/test_connectionpool.py
index 2e84a5370..bc6a7878e 100644
--- a/test/with_dummyserver/test_connectionpool.py
+++ b/test/with_dummyserver/test_connectionpool.py
@@ -12,8 +12,7 @@
 from .. import (
     TARPIT_HOST,
     VALID_SOURCE_ADDRESSES,
-    INVALID_SOURCE_ADDRESSES,
-    requires_network
+    INVALID_SOURCE_ADDRESSES
 )
 from ..port_helpers import find_unused_port
 from urllib3 import (
@@ -884,7 +883,11 @@ def test_redirect_cross_host_forward_auth_headers(self):
         headers = {'Authentication': 'foo'}
         retry = Retry(redirect=2, forward_auth_headers_across_hosts=True)
 
-        resp = self.pool.urlopen('GET', url, headers=headers, assert_same_host=False, retries=retry)
+        resp = self.pool.urlopen(
+            'GET', url, headers=headers,
+            assert_same_host=False,
+            retries=retry
+        )
 
         self.assertEqual(resp.status, 200)
 
